ploop/fairsched/io_prio: compilation fixes
Some problems were detected during compilation procedure

| drivers/block/ploop/dev.c:4343:2: error: initialization from incompatible pointer type [-Werror]
|   .release =  ploop_release,
|   ^

	The block_device_operations uses "void" for @release

| fs/sysfs/ve.c: In function ‘sysfs_perms_open’:
| fs/sysfs/ve.c:284:17: error: unused variable ‘cftype’ [-Werror=unused-variable]
|   struct cftype *cftype = file->f_dentry->d_fsdata;
|                  ^

	Unused variable

| In file included from fs/proc/stat.c:11:0:
| include/linux/fairsched.h:56:54: error: ‘struct cgroup’ declared inside parameter list [-Werror]
|  void cpu_cgroup_get_stat(struct cgroup *cgrp, struct kernel_cpustat *kstat);
|                                                       ^
| include/linux/fairsched.h:56:54: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]
| include/linux/fairsched.h:59:35: error: ‘struct cgroup’ declared inside parameter list [-Werror]
|  int cpu_cgroup_get_avenrun(struct cgroup *cgrp, unsigned long *avenrun);
|                                    ^
| include/linux/fairsched.h:64:12: error: ‘struct cgroup’ declared inside parameter list [-Werror]
|      struct seq_file *p);
|             ^

	Need to include linux/cgroup.h and linux/seq_file.h

Finally unused ioprio_weight variable.

Signed-off-by: Cyrill Gorcunov <gorcunov@openvz.org>