vznetstat: fix compilation
This is a port of following vzcommits:
    vzcommit: 5b7840880d1f8255e0f6a4706632bd5e91b4f75c

    vznetstat: fix compilation

    This patch enables vznetstat module in Makefile and
    fixes some compilation errors. But modules still will
    not work correctly.

    https://jira.sw.ru/browse/PSBM-20094

    Signed-off-by: Dmitry Guryanov <dguryanov@parallels.com>
    Acked-by: Stanislav Kinsbursky <skinsbursky@parallels.com>

=====
    vzcommit: 2ee8e739e0a7ebb2b8dc9ec00d38eabb0777b492
    (vznetstat part of it)

    vznetstat/vzredir: compilation fix warning: initialization from incompatible pointer type

    Fixed compilation warning found in x64, gcc 4.8.3

    Build log:
    /mnt/sources/linux-3.9-vzmodules/vznetstat/ip6_vznetstat.c:62:2: warning: initialization from incompatible pointer type [enabled by default]
      .hook  = venet_acct_in_hook_v6,
      ^
    /mnt/sources/linux-3.9-vzmodules/vznetstat/ip6_vznetstat.c:62:2: warning: (near initialization for ‘venet_acct_in_ops.hook’) [enabled by default]
    /mnt/sources/linux-3.9-vzmodules/vznetstat/ip6_vznetstat.c:70:2: warning: initialization from incompatible pointer type [enabled by default]
      .hook  = venet_acct_out_hook_v6,

    Signed-off-by: Andrey Smetanin <asmetanin@parallels.com>
    Acked-by: Vladimir Davydov <vdavydov@parallels.com>

    khorenko@:
    RHEL7 3.10.0-123.1.2.el7 kernel has modified struct nf_hook_ops,
    so need to modify our hooks accordingly.

Signed-off-by: Konstantin Khorenko <khorenko@parallels.com>