vdso, vclock_gettime: fix linking with old linkers
On some old linkers vdso fails to build because of
dynamic reloction of 've_start_time' symbol:
	VDSO2C  arch/x86/entry/vdso/vdso-image-64.c
	Error: vdso image contains dynamic relocations

I was able to figure out why new linkers doesn't generate relocation
while old ones does, but I did find out that visibility("hidden")
attribute on 've_start_time' cures the problem.

Fixes: af2c78f571e6 ("ve: add per-ve CLOCK_MONOTONIC time via
__vdso_gettimeofday()")

https://jira.sw.ru/browse/PSBM-121668
Signed-off-by: Andrey Ryabinin <aryabinin@virtuozzo.com>