vznetstat: apply vznetstat patches from 2.6.32 as is
vzcommit: 1f5023a971dc1aa550ef2cbdc91462f705e6a765
https://jira.sw.ru/browse/PSBM-20094

Signed-off-by: Dmitry Guryanov <dguryanov@parallels.com>
Acked-by: Stanislav Kinsbursky <skinsbursky@parallels.com>

Changes:
  * license set to "GPL v2"
  * copyright message added

Signed-off-by: Konstantin Khorenko <khorenko@parallels.com>

+++
vznetstat: fix compilation

This is a port of following vzcommits:
    vzcommit: 5b7840880d1f8255e0f6a4706632bd5e91b4f75c

    vznetstat: fix compilation

    This patch enables vznetstat module in Makefile and
    fixes some compilation errors. But modules still will
    not work correctly.

    https://jira.sw.ru/browse/PSBM-20094

    Signed-off-by: Dmitry Guryanov <dguryanov@parallels.com>
    Acked-by: Stanislav Kinsbursky <skinsbursky@parallels.com>

=====
    vzcommit: 2ee8e739e0a7ebb2b8dc9ec00d38eabb0777b492
    (vznetstat part of it)

    vznetstat/vzredir: compilation fix warning: initialization from incompatible pointer type

    Fixed compilation warning found in x64, gcc 4.8.3

    Build log:
    /mnt/sources/linux-3.9-vzmodules/vznetstat/ip6_vznetstat.c:62:2: warning: initialization from incompatible pointer type [enabled by default]
      .hook  = venet_acct_in_hook_v6,
      ^
    /mnt/sources/linux-3.9-vzmodules/vznetstat/ip6_vznetstat.c:62:2: warning: (near initialization for ‘venet_acct_in_ops.hook’) [enabled by default]
    /mnt/sources/linux-3.9-vzmodules/vznetstat/ip6_vznetstat.c:70:2: warning: initialization from incompatible pointer type [enabled by default]
      .hook  = venet_acct_out_hook_v6,

    Signed-off-by: Andrey Smetanin <asmetanin@parallels.com>
    Acked-by: Vladimir Davydov <vdavydov@parallels.com>

    khorenko@:
    RHEL7 3.10.0-123.1.2.el7 kernel has modified struct nf_hook_ops,
    so need to modify our hooks accordingly.

Signed-off-by: Konstantin Khorenko <khorenko@parallels.com>

+++
vznetstat: remove redirection remains

Some checks left after we decided to remove
redirection code, so drop them as well.

https://jira.sw.ru/browse/PSBM-32912

Signed-off-by: Konstantin Khorenko <khorenko@openvz.org>

+++
ve/net: drop sk_buff->accounted

It is not used anywhere.

Signed-off-by: Vladimir Davydov <vdavydov@parallels.com>

+++
vznetstat: don't use vehooks

This is a port of vznetstat part of
    vzcommit: 3ab92941f4f6bfd6fb38c68d83dc89d7b175d029

    vznetstat: don't use vehooks

    It's possible to allocate and free venet_stat structure
    directly from venet code, avoiding ve hooks.

    Allocation and setting pointer ve_struct->stat should be done
    in veip_create function in vzredir. We need to do it before
    ip address appear on venet device inside running container.

    Freeing and setting ve_struct to NULL should be done after
    stopping venet device, so no packets could reach iptables
    hooks from ip_vznetstat modules (NF_INET_LOCAL_IN).
    So net device destructor is a good place for it.

    https://jira.sw.ru/browse/PSBM-20094

    Signed-off-by: Dmitry Guryanov <dguryanov@parallels.com>
    Acked-by: Stanislav Kinsbursky <skinsbursky@parallels.com>

+++
vznetstat: alloc ve->stat if necessary

Module ip6_vznetstat depends on ip_vznetstat. In 2.6.32 we used
to alloc stat for in ip_vznetstat VE hooks, but after 81735c48d90e
"vznetstat: don't use vehooks" we do not do that. Statistics is
allocated in vzredir (see 7e5ce29122c6 "vzredir: uncomment vznetstat calls").

So, if vzredir module is not loaded, we fail to complete ip6_vznetstat
pernet init operation, and a CT fails to start. Fix that.

https://jira.sw.ru/browse/PSBM-32072

Signed-off-by: Kirill Tkhai <ktkhai@parallels.com>

+++
ve: add config options for vzlist and vznetstat modules

Port diff-vz-hookin-generic-3

+ CONFIG_VZ_LIST
+ CONFIG_VE_NETDEV_ACCOUNTING

https://jira.sw.ru/browse/PSBM-19217

Signed-off-by: Kirill Tkhai <ktkhai@odin.com>

+++
ve: drop not used CAP_VE_ADMIN and CAP_VE_NET_ADMIN

Not needed anymore as we use user ns for capability checking.
Also, move capable_setveid() helper to ve.h so as not to pollute
generic headers.

Signed-off-by: Vladimir Davydov <vdavydov@virtuozzo.com>

=============================================================================

vznetstat: Port diff-vznetstat-fix-ip_vznetstat-module-load

Author: Dmitry Guryanov
Email: dguryanov@parallels.com
Subject: NET: fix ip_vznetstat module load
Date: Fri, 17 May 2013 15:03:11 +0400

If we start some containers, then load module ip_vznetstat -
ve_struct->stat pointer will not be initialized and we will
get kernel panic with first incoming packet.

So initialize all pointers, not only in ve0.

BUG https://jira.sw.ru/browse/PCLIN-31771

Signed-off-by: Dmitry Guryanov <dguryanov@parallels.com>

Acked-by: Andrey Vagin <avagin@openvz.org>

changes in v2:
        ve_hook_register(VE_SS_CHAIN, &venet_acct_hook);
        moved before stat pointers initialization, because in previous
        version contaiers, created after mutex_unlock and before
        ve_hook_register wouldn't be initialized.

changes in v3:
        remove module_get/put on ct start/stop, so that we can
        unload module.

changes in v4:
	unregister vz hooks before freeing venet_stat structures

 net/ipv4/netfilter/ip_vznetstat.c |   50 ++++++++++++++++++++++++------------
 1 files changed, 33 insertions(+), 17 deletions(-)
=============================================================================

Author: Vasily Averin
Email: vvs@parallels.com
Subject: ip_venetstat_init: access to ve_list without proper locking
Date: Fri, 12 Sep 2014 14:02:12 +0400

ip_venetstat_init() on error path uses for_each_ve() without proper locking.
Access to ve_llust head should be protected by ve_list_lock.

Signed-off-by: Vasily Averin <vvs@parallels.com>
=============================================================================

Related to https://jira.sw.ru/browse/PSBM-33650

Signed-off-by: Vladimir Davydov <vdavydov@parallels.com>

=============================================================================

vznetstat: Use kzalloc instead of kmalloc plus memset

Signed-off-by: Cyrill Gorcunov <gorcunov@openvz.org>

=============================================================================

vznetstat: Make sure the statistics is allocated for VE

Currently the ip_vznetstat doesn't allocate statistics for new
VEs but rather relies on fact that ip6_vznetstat module is loaded,
which is not always the true. It's rather messy at moment:
ip_vznetstat allocates stat for all existing VE's in module
init procedure, while ip6_vznetstat allocates statistics for
every new VE's, better might be to move all this stuff into
general vznetstat module in future.

https://jira.sw.ru/browse/PSBM-34837

Signed-off-by: Cyrill Gorcunov <gorcunov@virtuozzo.com>

CC: Andrey Vagin <avagin@virtuozzo.com>
CC: Vladimir Davydov <vdavydov@virtuozzo.com>
CC: Konstantin Khorenko <khorenko@virtuozzo.com>
CC: Igor Sukhih <igor@parallels.com>

=============================================================================

ve/vznetstat: Move VE networks statistics allocation into a common place

We have three modules serving network statictics:

 - vznetstat.ko
 - ip_vznetstat.ko
 - ip6_vznetstat.ko

where ip6_vznetstat depends on ip_vznetstat and both depends on general vznetstat
module. While vznetstat does are real work on network packets counting the
counters are allocated in somehow nontrivial way

 1) ip_vznetstat depends on ip6_vznetstat, and both require vznetstat module
 2) when ip_vznetstat loads it walks over all existing VE and allocates counters
    setting up a ve-startup hook to allocate counters for VE which will be
    started after
 3) in turn ip6_vznetstat module doesn't depend on ip_vznetstat (which does
    a real counters allocations, in commit 3ad7b9565dc63734 we fixed
    ip6_vznetstat so it allocates counters for newly created VEs if
    former ip_vznetstat get unloaded, but this doesn't take existing
    VEs into account)

This makes counters allocation code really hard to read. Lets do their
allocation in a different way

 - move counters allocation into general vznetstat module, upon its
   load it does:

   * walk over all existing running VEs and allocate/get counters
   * setup VE start/stop hooks to allocate/get counters for further
     VEs which be started after the module load

 - drop counters allocation from both ip6_vznetstat and ip_vznetstat,
   these modules simply register netfilter hooks for incoming/outgoing
   traffic and count packets

 - drop ip_vznetstat dependency on ip6_vznetstat, they are not bound
   anymore and each simply depends on general vznetstat module which
   allocates counters for them

https://jira.sw.ru/browse/PSBM-35011

v2:
 - don't forget to assign newly created counters into VEs

v3:
 - switch to per-net operaions: instead of using start/stop
   hooks we simply register net init/exit hooks which either
   create/get or put/destroy the statistics. Note there is
   no longer module-get/put, we rely on net namespace
   synchronization, thus one can call rmmod over all
   modules mentioned above even with running VEs.

Signed-off-by: Cyrill Gorcunov <gorcunov@virtuozzo.com>
Reviewed-by: Vladimir Davydov <vdavydov@parallels.com>

CC: Andrey Vagin <avagin@virtuozzo.com>
CC: Konstantin Khorenko <khorenko@virtuozzo.com>
CC: Pavel Emelyanov <xemul@virtuozzo.com>
CC: Igor Sukhih <igor@parallels.com>

=============================================================================

ve/vznetstat: Don't destroy statistics until explicitly asked

When I've been reworking vznetstat mem management I've added destroying
of VE's statistics upon containers stop. This is incorrect, we need to
keep it while module is alive.

Still one can destroy statistics with VZCTL_TC_DESTROY_STAT
or VZCTL_TC_DESTROY_ALL_STAT (of course it clears it for
non running VEs only).

https://jira.sw.ru/browse/PSBM-35178

v2 (by vdavydov@):
 - clear ve::stat in net_exit_acct instead of bunch
   cleanup on module exit

Signed-off-by: Cyrill Gorcunov <gorcunov@virtuozzo.com>

CC: Andrey Vagin <avagin@virtuozzo.com>
CC: Vladimir Davydov <vdavydov@virtuozzo.com>
CC: Konstantin Khorenko <khorenko@virtuozzo.com>
CC: Pavel Emelyanov <xemul@virtuozzo.com>
CC: Igor Sukhih <igor@parallels.com>

+++
ve/vznetstat: Fix potential exit race

When container is exiting another task may be doing operations
with statistics incrementing/decrementing stat counter, which
may lead to situation where counter is not zero, thus we don't
zap @ve->stat member.

Fix it by testing if the net is the last one belonging
to a container.

https://jira.sw.ru/browse/PSBM-35178

mFixes: 505f8aacf95dce27fad66c90d4e1cd64adcb5432
(ve/vznetstat: Don't destroy statistics until explicitly asked)

Signed-off-by: Cyrill Gorcunov <gorcunov@virtuozzo.com>

CC: Andrey Vagin <avagin@virtuozzo.com>
CC: Vladimir Davydov <vdavydov@virtuozzo.com>
CC: Konstantin Khorenko <khorenko@virtuozzo.com>
CC: Pavel Emelyanov <xemul@virtuozzo.com>
CC: Igor Sukhih <igor@parallels.com>

=============================================================================

ve/vznetstat: fix RCU-protected "info_V{4, 6}" pointers initialization

This pointers have to be referenced and assigned under rcu_read_lock().
Moreover, there is no need to take tc_lock: it protects stats hash, but not
info pointers.

Fixes the following warning:

[   31.658913] ===============================
[   31.659035] [ INFO: suspicious RCU usage. ]
[   31.659155] 3.10.0+ #121 Not tainted
[   31.659258] -------------------------------
[   31.659377] kernel/ve/vznetstat/vznetstat.c:95 suspicious
rcu_dereference_check() usage!
[   31.659597]
[   31.659597] other info that might help us debug this:
[   31.659597]
[   31.659831]
[   31.659831] rcu_scheduler_active = 1, debug_locks = 0
[   31.660026] 1 lock held by vztactl/831:
[   31.660136]  #0:  (tc_lock){.+.+..}, at: [<ffffffffa0052e64>]
venet_acct_set_classes+0xf4/0x240 [vznetstat]
[   31.660454]
[   31.660454] stack backtrace:
[   31.660584] CPU: 0 PID: 831 Comm: vztactl ve: 0 Not tainted 3.10.0+ #121
ovz.9.8-21-g6c64ed7
[   31.660823] Hardware name: Parallels Software International Inc. Parallels
Virtual Platform/Parallels Virtual Platform, BIOS 6.9.23856.1122235 03/18/2015
[   31.661201]  0000000000000000 000000003e77c710 ffff8800a960bd88
ffffffff816298fe
[   31.661436]  ffff8800a960bdb8 ffffffff810f9667 0000000000000000
ffff8801446e2f08
[   31.661661]  0000000000000000 000000000000000c ffff8800a960bdf0
ffffffffa0052f61
[   31.661910] Call Trace:
[   31.661989]  [<ffffffff816298fe>] dump_stack+0x19/0x1b
[   31.662134]  [<ffffffff810f9667>] lockdep_rcu_suspicious+0xe7/0x120
[   31.662308]  [<ffffffffa0052f61>] venet_acct_set_classes+0x1f1/0x240
[vznetstat]
[   31.662511]  [<ffffffffa005390b>] venet_acct_ioctl+0x2bb/0xaf0 [vznetstat]
[   31.662706]  [<ffffffffa003f0d5>] vzctl_ioctl+0x45/0x60 [vzdev]
[   31.662875]  [<ffffffff812296d5>] do_vfs_ioctl+0x265/0x540
[   31.663041]  [<ffffffff81236177>] ? fget_light+0x377/0x4e0
[   31.663193]  [<ffffffff81229a04>] SyS_ioctl+0x54/0xa0
[   31.663334]  [<ffffffff8163bf09>] system_call_fastpath+0x16/0x1b

Signed-off-by: Stanislav Kinsburskiy <skinsbursky@virtuozzo.com>

=============================================================================

uapi/bc/netstat: add comments about possible leaks

For now copy_to_user on those structures are safe, but that may
be changed with future struct extensions.

https://jira.sw.ru/browse/PSBM-52219

Cc: Maxim Patlasov <mpatlasov@virtuozzo.com>
Signed-off-by: Dmitry Safonov <dsafonov@virtuozzo.com>

+++ vz7.39.x
vznetstat: Add protection to venet_acct_set_classes()

It seems there was no synchronization since the time
when ioctls in kernel were serialized via single mutex.

Signed-off-by: Kirill Tkhai <ktkhai@virtuozzo.com>
Acked-by: Andrey Ryabinin <aryabinin@virtuozzo.com>

+++
vznetstat: Convert some kmalloc()/kfree() to __vmalloc()/vfree()

Let's use virtually continuos pages instead of physically continuos
as it's easier to allocate them.

Also, add __GFP_NOWARN to not disturb a user in case of ENOMEM.

https://jira.sw.ru/browse/PSBM-79502

Signed-off-by: Kirill Tkhai <ktkhai@virtuozzo.com>
Acked-by: Andrey Ryabinin <aryabinin@virtuozzo.com>

khorenko@: the reason for that: we faced so huge table that
it required 5-order page allocation.