configs: minimal "yes"-config added for KVM VM
How it was created:
1) take the vz8 kernel
2) build with kernel-4.18.0-x86_64.config
3) boot the kernel on vz7 KVM VM
4) do "make localyesconfig"
5) enable some more options which could be useful later
   (IPVS, netfilters, VLAN)

Signed-off-by: Konstantin Khorenko <khorenko@virtuozzo.com>

+++
configs: Enable CONFIG_DM_CRYPT option for encrypted containers

This is needed for dm_crypt over ploop.

Signed-off-by: Kirill Tkhai <ktkhai@virtuozzo.com>

+++
configs: Enable CONFIG_BLK_DEV_LOOP option

Ploop target uses loop as origin device

Signed-off-by: Kirill Tkhai <ktkhai@virtuozzo.com>

+++
config.OpenVZ.minimal: disable XEN support and align other options

We don't need XEN support in minimal KVM config.
+ the minimal config lacks some other config options, add them.

Signed-off-by: Konstantin Khorenko <khorenko@virtuozzo.com>

+++
config.minimal: add configs required for criu to config.OpenVZ.minimal

See https://criu.org/Linux_kernel:

CONFIG_UNIX_DIAG
CONFIG_INET_DIAG
CONFIG_INET_UDP_DIAG
CONFIG_PACKET_DIAG
CONFIG_NETLINK_DIAG
CONFIG_NETFILTER_XT_MARK
CONFIG_MACVLAN
CONFIG_MEM_SOFT_DIRTY

Also I've mentined that these modules were also loaded when running zdtm
on full config.OpenVZ build so I also added them:

CONFIG_INET_TCP_DIAG
CONFIG_INET_RAW_DIAG
CONFIG_NF_CT_NETLINK
CONFIG_NFT_COUNTER
CONFIG_NETFILTER_XT_SET
CONFIG_NETFILTER_XT_MATCH_CONNTRACK
CONFIG_NETFILTER_XT_MATCH_STATE
CONFIG_IP_SET_HASH_NET
CONFIG_IP_VS_NFCT
CONFIG_IP_NF_MANGLE
CONFIG_IP6_NF_FILTER
CONFIG_IP6_NF_MANGLE
CONFIG_BRIDGE_VLAN_FILTERING
CONFIG_NFSD
CONFIG_IPV6_SIT

https://jira.sw.ru/browse/PSBM-101289

v2: add CONFIG_IPV6_SIT

Signed-off-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>

+++
config.minimal: Aling minimal config options for RHEL8.3 based kernel

Signed-off-by: Konstantin Khorenko <khorenko@virtuozzo.com>

+++
config.OpenVZ.minimal: Add NETFILTER_XT_NAT, IP_NF_NAT, IP_NF_TARGET_MASQUERADE

VZ services (and thus containers) fail to start without them.

Signed-off-by: Kirill Tkhai <ktkhai@virtuozzo.com>

+++
config.OpenVZ.minimal: disable CONFIG_X86_DECODER_SELFTEST

CONFIG_X86_DECODER_SELFTEST is time consuming check which not
required during development phase. Let's disable it.

Compilation time comparison
        with opt   w/o option
real    1m31.293s  0m45.884s
user    1m57.299s  1m1.084s
sys     0m17.724s  0m14.527s

Signed-off-by: Dmitry Monakhov <dmonakhov@openvz.org>

(cherry picked from vz7 commit a817fdbed90d ("config.OpenVZ.minimal: disable
CONFIG_X86_DECODER_SELFTEST"))

VZ 8 rebase part https://jira.sw.ru/browse/PSBM-127797

Signed-off-by: Alexander Mikhalitsyn <alexander.mikhalitsyn@virtuozzo.com>

+++
config.OpenVZ.minimal: rebase to RHEL8.4 base kernel

+ enable CONFIG_HYPERV, otherwise compilation fails in many places, not
touched by us

arch/x86/kernel/kvm.c:285:15: error: 'irq_cpustat_t' {aka 'struct
<anonymous>'} has no member named 'irq_hv_callback_count'; did you mean
'irq_call_count'?

https://jira.sw.ru/browse/PSBM-131158

Signed-off-by: Konstantin Khorenko <khorenko@virtuozzo.com>

+++
configs: Enable scsi configuration options in minimal config

We had the same in vz7 minimal config:

+CONFIG_SCSI_ISCSI_ATTRS=y
+CONFIG_ISCSI_TCP=y
+CONFIG_ISCSI_BOOT_SYSFS=y

Else there can be error when booting in this kernel in VM: "dracut:
FATAL: iscsiroot requested but kernel/initrd does not support iscsi"

Signed-off-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>