ve/vtty: fix mixed declarations and code in vtty_release()
Compilation error fixed:

drivers/tty/pty.c: In function 'vtty_release':
drivers/tty/pty.c:1266:2: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
  int pty_master;
  ^

Fixes commit 26d58a8eea6ea ("ve/vtty: Don't close unread master peer if slave is nonzero")

Signed-off-by: Konstantin Khorenko <khorenko@virtuozzo.com>