Revert "VE: export more headers to userspace"
This reverts commit 36b11fff7248964b50327f2ccf7edf8d176d1550.

Headers must be fixed before export, otherwise we get compilation errors like:

...include/linux/compat.h:286: userspace cannot reference function or variable defined in the kernel
...include/linux/fairsched.h:14: included file 'linux/cgroup.h' is not exported

https://jira.sw.ru/browse/PSBM-31973

Signed-off-by: Konstantin Khorenko <khorenko@openvz.org>