ve/fs/binfmt: virtualization
* keep deference from binfmt_misc sb to ve
* store pointer to binfmt_misc data in ve->binfmt_misc

Here bm_put_super() can race with load_misc_binary() caller, which is working
with get_exec_env()->binfmt_misc.
Will be fixed separately.

Signed-off-by: Konstantin Khlebnikov <khlebnikov@openvz.org>

+++
VE/BINFTM: fix destruction ordering

kill binfmt_data together with ve_struct

Signed-off-by: Konstantin Khlebnikov <khlebnikov@openvz.org>

+++
ve/binfmt_misc: fix compilation outside CONFIG_BINFMT_MISC

Fix for the next compile error:
kernel/ve/ve.c: In function ‘ve_destroy’:
kernel/ve/ve.c:709:10: error: ‘struct ve_struct’ has no member named ‘binfmt_misc’
  kfree(ve->binfmt_misc);

mFixes 4b7d610d45498ac733e92024097dc99402476b27
("VE/BINFTM: fix destruction ordering").

Signed-off-by: Dmitry Safonov <dsafonov@virtuozzo.com>

+++
ve/binfmt_misc: do not use sb->s_fs_info

Patchset description:

zap sb->s_ns + fix memleak in binfmt_misc

Vladimir Davydov (6):
  binfmt_misc: do not use sb->s_fs_info
  Revert "VE/VFS: use sb->s_ns member to store namespace for mount_ns()
    calls"
  Revert "ve/sunrpc: use correct pointer to net_namespace in auth_gss.c"
  Revert "nfsd/sunrpc/mqueue: use sb->s_ns instead of data in
    fill_super"
  binfmt_misc: do not use s_ns
  binfmt_misc: destroy all nodes on ve stop

https://jira.sw.ru/browse/PSBM-39154

Reviewed-by: Cyrill Gorcunov <gorcunov@virtuozzo.com>

======================
This patch description:

When we virtualized binfmt_misc, we made sb->s_fs_info store a pointer
to binfmt_misc struct. At the same time, we store a pointer to the owner
ve_struct in sb->s_ns and a pointer to the same binfmt_misc struct in
ve_struct->binfmt_misc. That said, we don't actually need to use
s_fs_info, because we can get the binfmt_misc by dereferencing
sb->s_ns->binfmt_misc.

Using sb->s_fs_info instead of sb->s_ns will allow us to revert our
patches introducing sb->s_ns.

This could be merged to 0b0dbb644794 ("VE/BINFTM: virtualization").

Signed-off-by: Vladimir Davydov <vdavydov@parallels.com>

+++
ve/binfmt_misc: do not use s_ns

Patchset description:

zap sb->s_ns + fix memleak in binfmt_misc

Vladimir Davydov (6):
  binfmt_misc: do not use sb->s_fs_info
  Revert "VE/VFS: use sb->s_ns member to store namespace for mount_ns()
    calls"
  Revert "ve/sunrpc: use correct pointer to net_namespace in auth_gss.c"
  Revert "nfsd/sunrpc/mqueue: use sb->s_ns instead of data in
    fill_super"
  binfmt_misc: do not use s_ns
  binfmt_misc: destroy all nodes on ve stop

https://jira.sw.ru/browse/PSBM-39154

Reviewed-by: Cyrill Gorcunov <gorcunov@virtuozzo.com>

======================
This patch description:

Since 9e7411c5c3b5 was reverted, we must use sb->s_fs_info for storing a
pointer to the namespace.

This could be merged to 0b0dbb644794 ("VE/BINFTM: virtualization").

Signed-off-by: Vladimir Davydov <vdavydov@parallels.com>

+++
ve/fs: Use ve_printk in fs/binfmt_aout.c

This is a part of 74-diff-ve-mix-combined.

https://jira.sw.ru/browse/PSBM-17903

Signed-off-by: Kirill Tkhai <ktkhai@parallels.com>

======================

ve/fs: Allow to mount binfmt_misc under non-root ns

https://jira.sw.ru/browse/PSBM-40100

v2: Check that user_ns is initial for the ve.
v3: Be sure ve->init_cred is set.

Signed-off-by: Kirill Tkhai <ktkhai@odin.com>
Acked-by: Vladimir Davydov <vdavydov@virtuozzo.com>

khorenko@: in fact we allowed to do those mounts in top CT user ns only.

======================

ve/binfmt_misc: Allow mount if capable(CAP_SYS_ADMIN)

The patch allows to mount binfmt_misc in a CT with ve0's admin caps,
and it's need that for CRIU dump. This time, unmounted binfmt_misc
may be forced mounted back, and we don't want to change CRIU's user_ns
to do that.

https://jira.sw.ru/browse/PSBM-47737

Signed-off-by: Kirill Tkhai <ktkhai@virtuozzo.com>
Reviewed-by: Andrey Ryabinin <aryabinin@virtuozzo.com>