ms/vfs: syscall: Add move_mount(2) to move mounts around
Patchset description:
These syscalls were added as preparation step for new mount api (fsopen,
fsconfig, fsmount and fspick will be ported separately).

We can use them to implement "cross-namespace bind-mounting" like this:

fd = open_tree(AT_FDCWD, "/mnt", OPEN_TREE_CLONE);
setns(nsfd, CLONE_NEWNS);
move_mount(fd, "", AT_FDCWD, "/mnt2", MOVE_MOUNT_F_EMPTY_PATH);

This will allow us implementing feature of adding bindmounts to runing
container instead of having unreliable external propagations.

It is needed to VZ8, but does not apply cleanly so I will send it
separately.

https://jira.sw.ru/browse/PSBM-107263

Current patch description:
From: David Howells <dhowells@redhat.com>

Add a move_mount() system call that will move a mount from one place to
another and, in the next commit, allow to attach an unattached mount tree.

The new system call looks like the following:

	int move_mount(int from_dfd, const char *from_path,
		       int to_dfd, const char *to_path,
		       unsigned int flags);

Signed-off-by: David Howells <dhowells@redhat.com>
cc: linux-api@vger.kernel.org
Signed-off-by: Al Viro <viro@zeniv.linux.org.uk>

vfs: syscall: Add move_mount(2) to move mounts around
(cherry-picked from commit 2db154b3ea8e14b04fee23e3fdfd5e9d17fbc6ae)
uapi, x86: Fix the syscall numbering of the mount API syscalls [ver #2]
(cherry-picked from commit 9c8ad7a2ff0bfe58f019ec0abc1fb965114dde7d)
selinux: fix regression introduced by move_mount(2) syscall
(cherry-picked from commit 98aa00345de54b8340dc2ddcd87f446d33387b5e)

https://jira.sw.ru/browse/PSBM-107263
Signed-off-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>

+++
fixup for "ms/vfs: syscall: Add move_mount(2) to move mounts around"

Patch fixes broken compilation:
security/selinux/hooks.c: In function 'selinux_move_mount':
security/selinux/hooks.c:2823:2: error: passing argument 2 of 'path_has_perm' discards 'const' qualifier from pointer target type [-Werror]
  return path_has_perm(cred, to_path, FILE__MOUNTON);
  ^
security/selinux/hooks.c:1758:19: note: expected 'struct path *' but argument is of type 'const struct path *'
 static inline int path_has_perm(const struct cred *cred,
                   ^
cc1: all warnings being treated as errors
make[2]: *** [security/selinux/hooks.o] Error

to be merged with following vz7 patch
commit 2bb98f065973 ("ms/vfs: syscall: Add move_mount(2) to move mounts around")
Signed-off-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>