ms/tty/ppc: define TIOSAK (fix tty_ioctl() compilation)
This was found while tring to compile the kernel with a stock
config (i.e. no CONFIG_BEANCOUNTERS, CONFIG_VE etc.) and
boot it on IBM Power8.

=============================================================

Fix the following error:

  CC      drivers/tty/tty_io.o
drivers/tty/tty_io.c: In function ‘tty_ioctl’:
drivers/tty/tty_io.c:2843:7: error: ‘TIOSAK’ undeclared (first use in
this function)
  case TIOSAK:

This is an addition to commit 28f8dfa.

Signed-off-by: Kir Kolyshkin <kir@openvz.org>