ve/kernel: fix kernel_thread() compilation for !CONFIG_VE
This was found while tring to compile the kernel with a stock
config (i.e. no CONFIG_BEANCOUNTERS, CONFIG_VE etc.) and
boot it on IBM Power8.

=============================================================

This is a fix to commit 0800da0.

Variable ve_allow_kthreads is defined in kernel/ve/ve.c which is only
included if CONFIG_VE is set, otherwise we get this:

	kernel/fork.c: In function ‘kernel_thread’:
	kernel/fork.c:1723:7: error: ‘ve_allow_kthreads’ undeclared (first use
	in this function)
	  if (!ve_allow_kthreads && !ve_is_super(get_exec_env())) {

Signed-off-by: Kir Kolyshkin <kir@openvz.org>