ve/fs: add per-VE limit of mount points
https://jira.sw.ru/browse/PSBM-34438

(This fix was adapted from PCS6.)

It is possible for a container to create lots of mount points, which may
make operations with them slower. As some of these operations take
global locks (namespace_sem, vfsmount_lock), it might affect other
containers as well.

Let us limit the maximum number of mount points a VE may create. The
limit can be customized via /proc/sys/fs/ve-mount-nr knob.

Changes in v.3:

* Revisited VE-specific parts of the patch to reduce the impact on the
  generic code.

Changes in v.2:

* The situations where VE0 mounts something and another VE unmounts it
  seem to be of no concern. If so, it is OK not to alter struct  mount:
  the mount counter for a VE may become unbalanced but this is
  acceptable here.

* The sysctl knob is now defined alongside other VE sysctls.

Signed-off-by: Evgenii Shatokhin <eshatokhin@virtuozzo.com>

Acked-by: Stanislav Kinsburskiy <skinsbursky@virtuozzo.com>

Testing results:
This "mount bomb" ends with "cannot allocate memory" and makes no harm:
   https://github.com/avagin/ctb/blob/master/mounts/run.sh

=====================================

ve/fs: Print a message if a VE reaches its limit on mounts

This should help debugging the situations when alloc_vfsmnt() fails.

Rate-limiting is used to avoid the flood of such messages if the mount
limit is hit often.

v2: Print the name of the VE rather than its address.

Suggested in https://jira.sw.ru/browse/PSBM-42825

Signed-off-by: Evgenii Shatokhin <eshatokhin@virtuozzo.com>

=====================================

ve/fs: Use comparison of signed integers in ve_mount_allowed()

ve->mnr_nr is a signed integer which may become negative in some cases:
* if the increments and decrements of ve->mnr_nr race against each other
  and the decrements win;
* if something is mounted by one VE but unmounted by another VE.

sysctl_ve_mount_nr is unsigned.

So the comparison (ve->mnr_nr < sysctl_ve_mount_nr) can actually be
compiled as ((unsigned int)ve->mnr_nr < sysctl_ve_mount_nr).
ve_mount_allowed() would return 0 in that case and the mount operation
would fail as a result.

This patch fixes the problem.

https://jira.sw.ru/browse/PSBM-42825

Signed-off-by: Evgenii Shatokhin <eshatokhin@virtuozzo.com>

==========================================

ve/fs: convert per-VE number of currently mounted fs to atomic_t

At the moment ve->mnt_nr is not atomic and not guarded by any lock =>
convert it to atomic_t in order to avoid races on updates

https://jira.sw.ru/browse/PSBM-69880

Signed-off-by: Konstantin Khorenko <khorenko@virtuozzo.com>

Reviewed-by: Kirill Tkhai <ktkhai@virtuozzo.com>

==========================================

ve/fs: limit "fs.ve-mount-nr" sysctl with INT_MAX

sysctl "fs.ve-mount-nr" is unsigned int and is casted to "int" while
comparing values => if we set it to a value > INT_MAX, VE won't be able to
mount anything after that.
=> set a max value for sysctl == INT_MAX

https://jira.sw.ru/browse/PSBM-69880

Signed-off-by: Konstantin Khorenko <khorenko@virtuozzo.com>

Reviewed-by: Kirill Tkhai <ktkhai@virtuozzo.com>

===========================================

ve/fs/mount: pin mnt to a VE for correct number of mounts accounting

If a mount is done in one VE context and umount - in another,
counters ve->mnt_nr became unbalanced and this can cause denial
of new mounts due to per-VE numbre of mounts limit.

Additionally move related functions to fs/namespace.c to avoid adding
fs/mount.h into ve.h:
	ve_mount_nr_inc()
	ve_mount_nr_dec()
	ve_mount_allowed()

Example: mount is done from inside a CT, umount - from host =>
ve->mnt_nr gets incorrectly increased for a CT.

https://jira.sw.ru/browse/PSBM-69880

Signed-off-by: Konstantin Khorenko <khorenko@virtuozzo.com>

Reviewed-by: Kirill Tkhai <ktkhai@virtuozzo.com>

===========================================

VZ 8 rebase part https://jira.sw.ru/browse/PSBM-127782
vz7 commit: 32ea6a7 ("ve/fs: add per-VE limit of mount points")

Signed-off-by: Alexander Mikhalitsyn <alexander.mikhalitsyn@virtuozzo.com>

+++
ve/fs: Compilation fix: vz_fs_table[] initialization

kernel/ve/veowner.c:75:4: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
  { 0 }
    ^
kernel/ve/veowner.c:75:4: note: (near initialization for 'vz_fs_table[2]')

mFixes: 9872dca0f40c ("ve/fs: add per-VE limit of mount points")

Signed-off-by: Konstantin Khorenko <khorenko@virtuozzo.com>