ve/nf_log_syslog: virtualize packet logging per-ve
This adds a helper ve_log_printk to print message into the specific ve
syslog. We need a new helper as ve_printk is useless here as it always
takes ve from current task but for logging packets we need to log to
net->owner_ve syslog, current context can be unrelated.

We already had ve_log_printk name defined in printk.h, let's reuse it.

Note: there is ebt packet logging in ebt_log_packet, but let's not
virtualize it. As a) it has multiple places where printk calls need
replacement, b) everybody is switching to nft/iptables(nft) so having
this nft-only feature should be enough.

Need in vzt-neoltp suite_net_tcp_cmds.exec.iptables/nft testcases.

Feature: ve/printk: printk virtualization

https://jira.sw.ru/browse/PSBM-138110
Signed-off-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>

+++
netfilter: fix compilation error in nf_log_unknown_packet

net/netfilter/nf_log_syslog.c: In function 'nf_log_unknown_packet':
net/netfilter/nf_log_syslog.c:932:9: error: too few arguments to function 'nf_log_buf_close'
  932 |         nf_log_buf_close(m);
      |         ^~~~~~~~~~~~~~~~
In file included from net/netfilter/nf_log_syslog.c:25:
./include/net/netfilter/nf_log.h:100:6: note: declared here
  100 | void nf_log_buf_close(struct nf_log_buf *m, struct net *net);
      |      ^~~~~~~~~~~~~~~~

Signed-off-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>