ve/tty: TIOSAK Secure Attention Key ioctl
port of 2.6.32-x diff-tty-TIOSAK-Secure-Attention-Key-ioctl
ported by Dmitry Guryanov <dguryanov@parallels.com>

Signed-off-by: Konstantin Khlebnikov <khlebnikov@openvz.org>
Signed-off-by: Dmitry Guryanov <dguryanov@parallels.com>

Author: Konstantin Khlebnikov
Email: khlebnikov@openvz.org
Subject: tty: TIOSAK Secure Attention Key ioctl
Date: Fri, 17 Feb 2012 19:01:48 +0400

This patch exposes SAK function via ioctl().
Require CAP_SYS_ADMIN if argument isn't pty-master.

Very useful for securing conteiner's vtty.

https://jira.sw.ru/browse/PSBM-11881

Acked-by: Pavel Emelyanov <xemul@parallels.com>

Problem is that there is no any output to user on second attach (i.e., login
prompt, bash prompt or vim screen, etc.) till some key pressed for refresh.
User should remind what program he ran on last console attach and issue proper
refresh action. It is very inconvenient.

Decided to kill run processes on detach in order to make second attach behavior
the same as first one.

(cherry picked from commit 9017b750a1e09d9d67941f24deb9cfc495b9e856)
Signed-off-by: Konstantin Khorenko <khorenko@virtuozzo.com>

gorcunov@: PPC definition of ioctl code comes from commit
(b67c122d1cd2db8811d8cd39d04b3edd869afc53) by Kir Kolyshkin <kir@openvz.org>
 | This was found while tring to compile the kernel with a stock
 | config (i.e. no CONFIG_BEANCOUNTERS, CONFIG_VE etc.) and
 | boot it on IBM Power8.
 |
 | =============================================================
 |
 | Fix the following error:
 |
 |   CC      drivers/tty/tty_io.o
 | drivers/tty/tty_io.c: In function ‘tty_ioctl’:
 | drivers/tty/tty_io.c:2843:7: error: ‘TIOSAK’ undeclared (first use in
 | this function)
 |   case TIOSAK:
 |
 | This is an addition to commit 28f8dfa.

Keep it for backward compatibility.

Signed-off-by: Cyrill Gorcunov <gorcunov@virtuozzo.com>
Feature: tty: virtual Container console