ve: add per-ve CLOCK_MONOTONIC time via __vdso_gettimeofday()
Make possible to read virtualized container's CLOCK_MONOTONIC time
via __vdso_gettimeofday(). Record containers start time in per-ve
vdso and substruct it from the host's time on clock read.

https://jira.sw.ru/browse/PSBM-121668

Signed-off-by: Andrey Ryabinin <aryabinin@virtuozzo.com>
Reviewed-by: Konstantin Khorenko <khorenko@virtuozzo.com>

khorenko@ notes:
1) effectively we store in vdso area the same ve->start_time value.
   If a CT has been previously running, say 5 ns, we store in
   ve->start_time value (now - 5), so later monotonic_abs_to_ve()
   returns now - (ve->start_time) == now - (now - 5) == 5

2) introduced timespec_sub_ns() function has "inline" attribute - it is
   fine.
   The stock timespec_add_ns() has "__always_inline" attribute, but the
   function is static, so there will be different copies of the function anyway
   even if the function is used in other files.

3) timespec_sub_ns() is introduced for optimization:
   if we use timespec_add_ns(ns)+monotonic_time_to_ve(), there will be
   2 cycles of __iter_div_u64_rem().

===============================================
The original vz7 commit message (f7188f105626):

    ve/vdso: virtualized monotonic gettime through vdso

    We already have infrastructure for virtualized vdso, however we use
    it only to change LINUX_VERSION_NAME in container. Simply store container's
    start time - ve->start_timespec in vdso variable - VDSO64_ve_start_timespec,
    and use it in __vdso_clock_gettime() to calculate container's monotonic time.

    Make uts_arch_setup_additional_pages()/uts_prep_vdso_pages_locked() to always
    setup new vdso, since previous policy to setup vdso only if uts_ns->name.releas
e
    wouldn't work for virtualized __vdso_clock_gettime()

    https://jira.sw.ru/browse/PSBM-66451

    Signed-off-by: Andrey Ryabinin <aryabinin@virtuozzo.com>
    Reviewed-by: Dmitry Safonov <dsafonov@virtuozzo.com>

+++
x86_64, vclock_gettime: Use standart division instead of __iter_div_u64_rem()

timespec_sub_ns() historically uses __iter_div_u64_rem() for division.
Probably it's supposed to be faster

	/*
	 * Iterative div/mod for use when dividend is not expected to be much
	 * bigger than divisor.
	 */
	u32 iter_div_u64_rem(u64 dividend, u32 divisor, u64 *remainder)

However in our case ve_start_time may make dividend much bigger than divisor.
So let's use standard "/" instead of iterative one. With 0 ve_start_time
I wasn't able to see measurable difference, however with big ve_start_time
the difference is rather significant:

 # time ./clock_iter_div
real    1m30.224s
user    1m30.343s
sys     0m0.008s

 # time taskset ./clock_div
real    0m2.757s
user    0m1.730s
sys     0m0.066s

32-bit vdso doesn't like 64-bit division and doesn't link.
I think it needs __udivsi3(). So just fallback to __iter_div_u64_rem()
on 32-bit.

mFixes: af2c78f571e6 ("ve: add per-ve CLOCK_MONOTONIC time via __vdso_gettimeofday()")

https://jira.sw.ru/browse/PSBM-121856
Signed-off-by: Andrey Ryabinin <aryabinin@virtuozzo.com>

+++
vdso, vclock_gettime: fix linking with old linkers

On some old linkers vdso fails to build because of
dynamic reloction of 've_start_time' symbol:
	VDSO2C  arch/x86/entry/vdso/vdso-image-64.c
	Error: vdso image contains dynamic relocations

I was able to figure out why new linkers doesn't generate relocation
while old ones does, but I did find out that visibility("hidden")
attribute on 've_start_time' cures the problem.

mFixes: af2c78f571e6 ("ve: add per-ve CLOCK_MONOTONIC time via
__vdso_gettimeofday()")

https://jira.sw.ru/browse/PSBM-121668
Signed-off-by: Andrey Ryabinin <aryabinin@virtuozzo.com>