ve/fs: Compilation fix: vz_fs_table[] initialization
kernel/ve/veowner.c:75:4: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
  { 0 }
    ^
kernel/ve/veowner.c:75:4: note: (near initialization for 'vz_fs_table[2]')

Fixes: 9872dca0f40c ("ve/fs: add per-VE limit of mount points")

Signed-off-by: Konstantin Khorenko <khorenko@virtuozzo.com>