vecalls: Introduce VZCTL_GET_CPU_STAT ioctl
This vzctl ioctl still used by vzstat utility and dispatcher/libvirt
statistics reporting.
>From one point of view almost all data can be get from cpu cgroup of a
Container (missing data can be exported additionally),
but statistics is gathered often and ioctl is faster and requires less
cpu power => let it be for now.

The current patch is based on following vz7 commits:
  ecdce58b214c ("sched: Export per task_group statistics_work")
  a58fb58bff1c ("Use ve init task's css instead of opening cgroup via vfs")
  75fc174adc36 ("sched: Port cpustat related patches")

Signed-off-by: Konstantin Khorenko <khorenko@virtuozzo.com>
Reviewed-by: Andrey Ryabinin <aryabinin@virtuozzo.com>

+++
sched: Uninline css_tg()

Compilation with custom config fails:

kernel/ve/ve.c: In function ‘ve_get_cpu_avenrun’:
kernel/ve/ve.c:1679:27: error: inlining failed in call to always_inline ‘css_tg’: function body not available
 inline struct task_group *css_tg(struct cgroup_subsys_state *css);
                           ^~~~~~
kernel/ve/ve.c:1690:7: note: called from here
  tg = css_tg(css);
       ^~~~~~~~~~~

We may remove "inline" attribute, as compiler is clever enough
to make itself inlining in kernel/sched/sched.c.

Signed-off-by: Kirill Tkhai <ktkhai@virtuozzo.com>
Reviewed-by: Evgenii Shatokhin <eshatokhin@virtuozzo.com>

(cherry-picked from vz8 commit e5e88546c0ab ("vecalls: Introduce
VZCTL_GET_CPU_STAT ioctl"))

Signed-off-by: Nikita Yushchenko <nikita.yushchenko@virtuozzo.com>
Feature: ve: extra statistics (mm, latency)