Revert "fs/fuse: disable optimization fuse and kio_pcs in debug kernel"
This reverts commit a9e2fa6238289f6a47f3f1b321ed6c0d53b77777.

Reason: a lot of compilation errors like

  In file included from ././include/linux/compiler_types.h:58,
                   from <command-line>:
  ./arch/x86/include/asm/jump_label.h: In function ‘page_ref_inc’:
  ./include/linux/compiler-gcc.h:305:38: error: asm operand 0 probably doesn’t match constraints [-Werror]
   #define asm_volatile_goto(x...) do { asm goto(x); asm (""); } while (0)
                                        ^~~
  ./arch/x86/include/asm/jump_label.h:38:2: note: in expansion of macro ‘asm_volatile_goto’
    asm_volatile_goto("1:"
    ^~~~~~~~~~~~~~~~~

https://www.lkml.org/lkml/2019/3/20/63

Compilation errors can be fixed by adding "__always_inline" attributes
but there are too many of them. So just revert the patch as the stabilization
stage has passed long ago.

Signed-off-by: Konstantin Khorenko <khorenko@virtuozzo.com>