fixup for "ms/vfs: syscall: Add move_mount(2) to move mounts around"
Patch fixes broken compilation:
security/selinux/hooks.c: In function 'selinux_move_mount':
security/selinux/hooks.c:2823:2: error: passing argument 2 of 'path_has_perm' discards 'const' qualifier from pointer target type [-Werror]
  return path_has_perm(cred, to_path, FILE__MOUNTON);
  ^
security/selinux/hooks.c:1758:19: note: expected 'struct path *' but argument is of type 'const struct path *'
 static inline int path_has_perm(const struct cred *cred,
                   ^
cc1: all warnings being treated as errors
make[2]: *** [security/selinux/hooks.o] Error

to be merged with following vz7 patch
commit 2bb98f065973 ("ms/vfs: syscall: Add move_mount(2) to move mounts around")
Signed-off-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>