cbt/blkdev.h: fix compilation in case CONFIG_BLK_DEV_CBT is not set
Compilation errors:

In file included from fs/block_dev.c:16:0:
fs/block_dev.c: В функции «bd_write_size»:
include/linux/blkdev.h:1649:32: ошибка: оператор без побочного эффекта
[-Werror=unused-value]
 #define blk_cbt_update_size(b) (0)
                                ^
fs/block_dev.c:1043:2: замечание: in expansion of macro «blk_cbt_update_size»
  blk_cbt_update_size(bdev);
  ^
  CC      fs/ioprio.o

Signed-off-by: Stanislav Kinsburskiy <skinsbursky@virtuozzo.com>