fs/fuse kio: implement cs_stats statistics info
This statistic shows information about all cs's, directed to show how much and
what type of load the chunk servers are loaded on. Made by analogy with
.vstorage.info/cs_stats statistics of user-mod client.

example:
1025       5=WORK     4909       0          0          (95% <= 20, 99% <= 20)   (95% <= 20, 99% <= 20)   128877

Signed-off-by: Pavel Butsykin <pbutsykin@virtuozzo.com>

=====================
Patchset description:

Statistics for vstorage kernel fast-path

Vstorage provides plenty of statistics information via 'vstorage -c cl mnt-top',
but when it comes kernel fast-path, it doesn't work. All because mnt-top
command collects information from .vstorage.info directory, where vstorage-mount
provides a lot of different statistical information in the form of files, but
it was not implemented for for fast-path.

This patch-set is aimed to implementation of the support of some statistics
inforamtion files from .vstorage.info:
  cs_stats
  fstat
  fstat_lat
  iostat
  requests
Which will be located at "/sys/fs/fuse/connections/*mnt_id*/kio_stat/". This
will be enough to maintain vstorage mnt-top command for fast-path mount points.

https://pmc.acronis.com/browse/VSTOR-20979

Acked-by: Alexey Kuznetsov <kuznet@virtuozzo.com>

Pavel Butsykin (14):
  fs/fuse: add conn_ctl to fuse_conn struct
  fs/fuse kio: create sysfs stat directory
  fs/fuse kio: implement iostat statistics info
  fs/fuse kio: make interface pcs_kio_file_list() for listing kio files
  fs/fuse kio: make interface pcs_kio_req_list() for listing kio reqs
  fs/fuse kio: add retry counter for kio requests
  fs/fuse kio: implement pcs_strerror()
  fs/fuse kio: implement requests statistics info
  fs/fuse kio: implement fstat statistics info
  fs/fuse kio: implement fstat_lat statistics info
  fs/fuse kio: remove useless pcs_cs initialization
  fs/fuse kio: implement cs statistics accounting
  fs/fuse kio: convert rpc state id to string
  fs/fuse kio: implement cs_stats statistics info

+++
fs/fuse kio: fix gcc warning maybe-uninitialized in do_show_cs_stats()

The compiler doesn't understand that pcs_perf_rate_cnt and fuse_lat_stat
structures may not be initialized only if the number of possible cpu is zero,
and this is impossible.

gcc log:
fs/fuse/kio/pcs/fuse_stat.c: In function 'do_show_cs_stats':
fs/fuse/kio/pcs/fuse_stat.c:354:12: error: 'sync_ops_rate.rate' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  seq_printf(m, "%-10llu %d=%-8s %-10llu %-10llu %-11llu",
            ^
fs/fuse/kio/pcs/fuse_stat.c:354:12: error: 'write_ops_rate.rate' may be used uninitialized in this function [-Werror=maybe-uninitialized]
fs/fuse/kio/pcs/fuse_stat.c:354:12: error: 'read_ops_rate.rate' may be used uninitialized in this function [-Werror=maybe-uninitialized]
cc1: all warnings being treated as errors

mFixes: 049aa5f3a22c fs/fuse kio: implement cs_stats statistics info

Signed-off-by: Pavel Butsykin <pbutsykin@virtuozzo.com>
Feature: vStorage