ve/kmod: list of allowed to autoload in CT modules
Since now not only iptables modules are allowed to be loaded
upon request from inside a Container, the list of modules
allowed to be autoload from inside a CT are stored in ve0_allowed_mod.

* binfmt_misc added to this list
* module_payload_allowed function moved outside CONFIG_VE_IPTABLES, so it
is compiled compile with config disabled

* renamed ve0_am to ve0_ipt_am for better description
* module_payload_iptable_allowed() now returns -1 in case the module name
is not in the list of iptables modules
* fix misspelled enviroment -> environment in comment

https://jira.sw.ru/browse/PSBM-41216

Signed-off-by: Dmitry Safonov <dmsafonov@virtuozzo.com>
Acked-by: Kirill Tkhai <ktkhai@virtuozzo.com>

+++
ve/kmod: fix build without CONFIG_VE_IPTABLES

Fix the following:
kernel/kmod.c:395:6: error: redefinition of ‘module_payload_allowed’
 bool module_payload_allowed(const char *module)
      ^
In file included from include/linux/module.h:13:0,
                 from kernel/kmod.c:21:
include/linux/kmod.h:50:20: note: previous definition of ‘module_payload_allowed’ was here
 static inline bool module_payload_allowed(const char *module) { return true; }

mFixes f69aa25a82ac63ade637c3c115dd6b99f8f12f80
("ve/kmod: list of allowed to autoload in CT modules").

Signed-off-by: Dmitry Safonov <dsafonov@virtuozzo.com>

+++
ve/kmod: rename {,fs-}binfmt_misc in the autoload whitelist

Somehow I managed to miss it last time.

mFixes: commit 8b9a6bef982e ("ve/kmod: list of allowed to autoload in CT
modules")

https://jira.sw.ru/browse/PSBM-41216

Cc: Kirill Tkhai <ktkhai@virtuozzo.com>
Signed-off-by: Dmitry Safonov <dsafonov@virtuozzo.com>

khorenko@: the list should contain aliases, not module names.