ve/ppc: include ve.h in process.c
This was found while tring to compile the kernel with a stock
config (i.e. no CONFIG_BEANCOUNTERS, CONFIG_VE etc.) and
boot it on IBM Power8.

=============================================================

As get_exec_env() is defined in linux/ve.h we have to include it.
Fixes the following compile error:

	  CC      arch/powerpc/kernel/process.o
	In file included from arch/powerpc/kernel/process.c:20:0:
	arch/powerpc/kernel/process.c: In function ‘arch_align_stack’:
	include/linux/mm.h:1951:43: error: dereferencing pointer to incomplete
	type
	 #define randomize_va_space (get_exec_env()->_randomize_va_space)
						   ^
	arch/powerpc/kernel/process.c:1564:53: note: in expansion of macro
	‘randomize_va_space’
	  if (!(current->personality & ADDR_NO_RANDOMIZE) && randomize_va_space)
							     ^
	make[1]: *** [arch/powerpc/kernel/process.o] Error 1

This is an addition to commit 0c67100

Signed-off-by: Kir Kolyshkin <kir@openvz.org>