ve/vtty: Don't close unread master peer if slave is nonzero
When there are several files opened on /dev/console from inside
of a container and noone hooked on master peer, any close called
cause master peer to be freed with TTY_CLOSING bit set. So that
next "vzctl console $ctid $ttynum" call force kernel to allocate
new vtty pair and in result we can't login into the container.

We've woraround master close when there is an active slave assigned
but I miss the scenario when several fd = open(/dev/console) done and
then one calls for close(fd).

Lets test if master peer is about to close while there are still
active slave (and move it into vtty_release helper).

https://jira.sw.ru/browse/PSBM-41985
https://jira.sw.ru/browse/PSBM-41672

Signed-off-by: Cyrill Gorcunov <gorcunov@virtuozzo.com>
Reviewed-by: Vladimir Davydov <vdavydov@virtuozzo.com>

+++
ve/vtty: fix mixed declarations and code in vtty_release()

Compilation error fixed:

drivers/tty/pty.c: In function 'vtty_release':
drivers/tty/pty.c:1266:2: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
  int pty_master;
  ^

Fixes commit 26d58a8eea6ea ("ve/vtty: Don't close unread master peer if slave is nonzero")

Signed-off-by: Konstantin Khorenko <khorenko@virtuozzo.com>