net/mm/packet: Pre-account maximum socket buffer into cg memory (v3)
Packet sockets have incoming queue of packets that is only limited
with per-socket wmem buffer. Strictly speaking we should sum up
all the queues and charge them into kmem once new packet arrives,
but this will result in huge patch. Since there's typically quite
a few of packet sockets in container (tcpdump) we can just forward
charge the maximum socket rmem size into cg memory upon socket
creation.

changes:
* v2: renamed sock_get_current_memcg
* removed sock_put_memcg
* fixed stub prototype
* removed lost rcu_read_unlock
* v3: kmem charge/uncharge routines name changed in patch #2

https://jira.sw.ru/browse/PSBM-33584

Signed-off-by: Pavel Emelyanov <xemul@parallels.com>

+++
ve/net/packet: fix possible return of uninitialized var

net/packet/af_packet.c: In function ‘packet_create’:
net/packet/af_packet.c:2762:6: error: ‘err’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  int err;
      ^

This is fix for
b3b3c0a net/packet: Pre-account maximum socket buffer into cg memory (v3)

Signed-off-by: Konstantin Khorenko <khorenko@virtuozzo.com>

+++
net/packet: use try_get_mem_cgroup_from_mm

... instead of home home bred try_get_mem_cgroup_from_current, and zap
the latter.

Signed-off-by: Vladimir Davydov <vdavydov@parallels.com>

+++
ve/net/packet: do not account sock buffer to cg if kmem acct is off

Signed-off-by: Vladimir Davydov <vdavydov@parallels.com>

+++
net/packet: cleanup packet_sk_charge

 - Do not check mem_cgroup_sockets_enabled - it has nothing to do with
   tcp/udp buffers accounting, which enable this static key. A check if
   memcg_kmem_is_active is enough anyway.

 - Do not forget to put memcg if try_get_mem_cgroup_from_mm returned a
   kmem inactive memcg.

 - Use ACCESS_ONCE for reading sysctl_rmem_max, because it can change on
   the fly and we rely on it being constant.

 - Use memcg_charge_kmem instead of memcg_charge_kmem_nofail for
   charging sock packet buf, because we can dive into reclaim here.

Signed-off-by: Vladimir Davydov <vdavydov@parallels.com>

[VvS rh7-3.10.0-1062.4.1.el7 rebase]
 this patch accounts packets size in bytes and requires according
  charge/uncharge functions which does not exist in rhel77 kernels
anymore.
 Accounting will be switched to pages in following patches.
 Removed incorrect memcg_charge_kmem declaration in
include/linux/memcontrol.h