ve: vznetstat and dummy Makefiles altered for Kpatch build
When I try to prepare a binary patch for vzkernel 3.10.0-229.7.2* with
Kpatch, the kernel fails to build. Here are the commands and the
relevant part of the output:

  exec gcc -Wp,-MD,kernel/ve/vznetstat/.vznetstat.o.d -nostdinc
  -isystem /usr/lib/gcc/x86_64-redhat-linux/4.8.3/include
<...>
  -I/usr/local/share/kpatch/patch -ffunction-sections -fdata-sections
  -DMODULE '-DKBUILD_STR(s)=#s'
  '-DKBUILD_BASENAME=KBUILD_STR(vznetstat)'
  '-DKBUILD_MODNAME=KBUILD_STR(vznetstat)' -c -o
   kernel/ve/vznetstat/.tmp_vznetstat.o
   /home/user/.kpatch/src/kernel/ve/vznetstat/vznetstat.c
  Assembler messages:
  Fatal error: can't create kernel/ve/vznetstat/.tmp_vznetstat.o:
  No such file or directory
  make[3]: *** [kernel/ve/vznetstat/vznetstat.o] Error 2
  make[2]: *** [kernel/ve] Error 2
  make[1]: *** [kernel] Error
The directories kernel/ve/vznetstat/ and kernel/ve/dummy/ were not
created in the build tree automatically in this case. If I create
these directories manually, the build completes successfully.

kpatch-build only provides thin wrappers for the compiler and such
to copy the resulting object files elsewhere. The kernel build
system is then used as is, so the problem is likely not in Kpatch.

kernel/ve/Makefile refers to vznetstat/* and dummy/* directly.

This patch makes sure these directories are explicitly added to the
build system. In my experiments, that was enough for both the normal
kernel builds and the Kpatch-based builds to complete successfully.

Note that *vznetstat*.ko modules will now be built in
kernel/ve/vznetstat/ rather than in kernel/ve/ as before, same for
the modules in kernel/ve/dummy/. As long as these modules are loaded
using modprobe and without explicit paths, it should be OK.

https://jira.sw.ru/browse/PSBM-40069

Signed-off-by: Evgenii Shatokhin <eshatokhin@odin.com>

khorenko@: filenames in new Makefile comments fixed