ms/net: ip, diag: include net/inet_sock.h
Patchset description:

These are backports from net-next tree. The patches are needed
to support c/r of raw sockets (criu part is to be implemented).

https://jira.sw.ru/browse/PSBM-51614

===
This patch description:

net-next: f8da977989c5d5d2f38e025d4ac1e18243723dbb

The newly added raw_diag.c fails to build in some configurations
unless we include this header:

In file included from net/ipv4/raw_diag.c:6:0:
include/net/raw.h:71:21: error: field 'inet' has incomplete type
net/ipv4/raw_diag.c: In function 'raw_diag_dump':
net/ipv4/raw_diag.c:166:29: error: implicit declaration of function 'inet_sk'

Fixes: 432490f9d455 ("net: ip, diag -- Add diag interface for raw sockets")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Cyrill Gorcunov <gorcunov@virtuozzo.com>