ve/sched/stat: Introduce functions to calculate vcpustat data
Signed-off-by: Konstantin Khorenko <khorenko@virtuozzo.com>
Reviewed-by: Andrey Ryabinin <aryabinin@virtuozzo.com>

+++
sched: Uninline css_tg()

Compilation with custom config fails:

kernel/ve/ve.c: In function ‘ve_get_cpu_avenrun’:
kernel/ve/ve.c:1679:27: error: inlining failed in call to always_inline ‘css_tg’: function body not available
 inline struct task_group *css_tg(struct cgroup_subsys_state *css);
                           ^~~~~~
kernel/ve/ve.c:1690:7: note: called from here
  tg = css_tg(css);
       ^~~~~~~~~~~

We may remove "inline" attribute, as compiler is clever enough
to make itself inlining in kernel/sched/sched.c.

Signed-off-by: Kirill Tkhai <ktkhai@virtuozzo.com>
Reviewed-by: Evgenii Shatokhin <eshatokhin@virtuozzo.com>