ve/kmod/whitelist: make nfnetlink_log autoloadable upon request from a CT
We see that k8s_weave-npc container fails with:

Thu Oct 29 09:19:53 2020 <5> ulogd.c:981 building new pluginstance stack: 'log1:NFLOG,base1:BASE,pcap1:PCAP'
Thu Oct 29 09:19:53 2020 <7> ulogd_inppkt_NFLOG.c:552 unable to bind to log group 86
Thu Oct 29 09:19:53 2020 <7> ulogd.c:948 error starting `log1'
Thu Oct 29 09:19:53 2020 <8> ulogd.c:1597 not even a single working plugin stack
Fatal error.

It needs nfnetlink_log module to be loaded. Need this to be able to run
kubernetes in centos-8 containers where it uses nft logs.

https://jira.sw.ru/browse/PSBM-121652

Signed-off-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>

(cherry picked from vz7 commit fdec083048f8 ("ve/kmod: make
nfnetlink_log autoloadable upon request from a CT")

Signed-off-by: Konstantin Khorenko <khorenko@virtuozzo.com>
Feature: kmod: whitelist of kernel modules able to autoload upon CT request