connector: introduce VE-aware get_cdev() helper
Once containerized, device won't be one and for all.
Thus make a helper template and use it instead of direct device object access.
Use ve0 for now.

Signed-off-by: Stanislav Kinsburskiy <skinsbursky@virtuozzo.com>
Reviewed-by: Andrey Ryabinin <aryabinin@virtuozzo.com>

[VvS RH77b]: compilation errors in drivers/connector/connector.c

patch fixes compilation error found during rebase to REHL77b kernel
3.10.0-1049.el7:

drivers/connector/connector.c: In function ‘get_cdev’:
drivers/connector/connector.c:65:12: error: dereferencing pointer to
incomplete type
  return &ve->cn->cdev;
            ^