net/ipv4: fib_semantics: omit excess rtm_flags
During ip route save we may get flags
RTNH_F_DEAD and RTNH_F_LINKDOWN in final dump image.
But we can't set these flags back during restore, because
these flags calculated dynamically in the kernel. It's
an inconsistency between NLM_F_DUMP and NLM_F_CREATE.

It's fully safe to workaround it just by ignoring such flags
in the kernel during RTM_NEWROUTE request processing.

Later, once my patches will be merged to mainstream we
can drop this commit.

Reproducer:
  $ ip link add type veth
  $ ip addr add 10.0.0.1/24 dev veth0
  $ ip link set veth0 up
  $ ip route add default via 10.0.0.1
  $ ip route save > route_dump
  $ ip route restore < route_dump
  Error: Invalid rtm_flags - can not contain DEAD or LINKDOWN.

Reference:
[RFC PATCH net-next] rtnetlink: add RTNH_F_REJECT_MASK
[RFC PATCH iproute2] ip route: save: exclude rtnh_flags which can't be set
https://lore.kernel.org/netdev/20211111160240.739294-1-alexander.mikhalitsyn@virtuozzo.com/T/#t

https://jira.sw.ru/browse/PSBM-135303
https://jira.sw.ru/browse/PSBM-140280

Signed-off-by: Alexander Mikhalitsyn <alexander.mikhalitsyn@virtuozzo.com>
Feature: fix net